version: "3.9"
services:
  chat-server:
    build: .
    container_name: "ribble-chat-server"
    depends_on:
      - chat-db
      - scylla
    ports:
      - "5000:5000"
      - "5001:5001"
  chat-db:
    image: "postgres:13.1"
    container_name: "ribble-chat-db"
    environment:
      POSTGRES_USER: "ribble-chat-server"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "ribble-chat-server"
    ports:
      - "5432:5432"
  # I know its not actually scylla yet but anyway...
  scylla:
    image: "cassandra"
    container_name: "ribble-scylla"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"


