version: "3.9"
services:
  chat-server:
    build: .
    container_name: "ribble-chat-server"
    depends_on: 
      - chat-db
    ports: 
      - "5000:5000"
      - "5001:5001"
  chat-db:
    image: "postgres:13.1"
    environment: 
      POSTGRES_USER: "ribble-chat-server"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "ribble-chat-server"
    ports: 
      - "5432:5432"
            
